apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: appdep
  name: appdep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appdep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: appdep
    spec:
      containers:
      - image: registry.rosish.me:5000/app:v.0
        name: image
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred
